### ISSUE TITLE
Symlinks not handled as small files.

### ISSUE THREAD

**Issue by misieck** [sahib/rmlint#396] opened 2020-01-29 03:53 UTC
Man pages claim --see-symlinks is default, but it doesn't appear to be. No symlinks are deduped. 
It does activate with -D, even for links outside of duplicate directories.

Bad symlinks: when I don't want to clean bad links, only remove duplicates, rmlint will not work as intended. Bad links are not listed, even preventing removal of duplicated directories containing bad links. The following will not work if bad links are present.

`rmlint -Dkm -T dd,df one // copy_of_one`

[onetwo.tar.gz](https://github.com/sahib/rmlint/files/4126064/onetwo.tar.gz)

**Comment by SeeSpotRun** [comment] 2021-03-27 03:34
Hi @misieck 

Sorry to take over a year to respond.

I'm unable to reproduce this issue.

Using your test folders:
```
$ rmlint -Dkm -T dd,df one // copy_of_one
# Duplicate Directorie(s):
    ls -la '/pwd/copy_of_one'
    rm -rf '/pwd/one'
```

Without `-T dd,df`, pretty much as expected:
```
$ rmlint -Dkm one // copy_of_one
# Bad symlink(s):
    rm '/pwd/one/onetwo.tar-1/one/badlinksinside/alink (copy)'
    rm '/pwd/one/onetwo.tar-1/one/alink'

# Duplicate Directorie(s):
    ls -la '/pwd/copy_of_one/onetwo.tar-1/one/src'
    rm -rf '/pwd/one/onetwo.tar-1/one/src'
    ls -la '/pwd/copy_of_one/onetwo.tar-1/one/simpleduplicate'
    rm -rf '/pwd/one/onetwo.tar-1/one/simpleduplicate'

# Duplicate(s):
    ls '/pwd/copy_of_one/onetwo.tar-1/one/mergerfs.balance'
    rm '/pwd/one/onetwo.tar-1/one/mergerfs.balance'
    ls '/pwd/copy_of_one/onetwo.tar-1/one/goodlink'
    rm '/pwd/one/onetwo.tar-1/one/goodlink'
    ls '/pwd/copy_of_one/onetwo.tar-1/one/badlinksinside/cider.JPG'
    rm '/pwd/one/onetwo.tar-1/one/badlinksinside/cider.JPG'
    ls '/pwd/copy_of_one/onetwo.tar-1/one/librmlint.a'
    rm '/pwd/one/onetwo.tar-1/one/librmlint.a'
```

Also the `--see-symlinks` default seems to work as expected:
```
$ mkdir links
$ cd links
$ echo data > links/file
$ ln -s "$(pwd)/links/file" links/link1
$ ln -s "$(pwd)/links/file" links/link1
$ ln -s /bad/link links/badlink1
$ ln -s /bad/link links/badlink1
$ rmlint ./links

# Bad symlink(s):
    rm '/pwd/links/badlink2'
    rm '/pwd/links/badlink1'

# Duplicate(s):
    ls '/pwd/links/link1'
    rm '/pwd/links/link2'

**Comment by SeeSpotRun** [comment] 2021-03-27 04:40
Ok it looks like this was fixed in Feb 2020: https://github.com/sahib/rmlint/commit/37e0c81c99648b35058ef2fbfaca89ee7fdd8b75.

Closing issue.

**Closed by SeeSpotRun** 2021-03-27 04:40 UTC
