### ISSUE TITLE
Running out of space during .sh generation. Script file not the cause. (btrfs clone)

### ISSUE THREAD

**Issue by nstgc** [sahib/rmlint#274] opened 2018-01-18 23:54 UTC
I've twice tried to run rmlint to free up some space on a raid0 btrfs volume today. This is not the first time I've done this, but rather something like the third or fourth, but this is the first time I've had this issue. The issue being that the volume fills up, but it doesn't appear to be caused by the script or Jason files being too large.

The first time today I was stupid I ran it in the volumes root, and assumed that the issue was the sh and/or json were too large. I deleted them, but that didn't do anything. I checked what had changed with btrfs sub find-new $PWD 0 |tail, but the only things that had changed were those two. The only other thing I could think of was that something got dereferenced. I ran btrfs fi df du and sh, all of which showed that the volume was full. Also, oddly, it got stuck at one point. I intrerupted it and it then kept going, eventually claiming to be able to free up 886GB of data on a 1TB volume. As far as I know, the amount of space freed shouldn't exceed 50% of the maximum capacity.

I deleted about 50 gigabytes worth of data, and tried again in a subvolume. Again, however the volume filled up. The resuting json and sh filers, however, were only about 200MBs total. A far cry from 50GB. I then deleted all snapshots which freed up 69GBs. Before I try again, I'd like to get some feed back and to what may be going on. I can't just keep deleting stuff.

As for the exact command used, it was sudo rmlint -T df --config=sh:handler=clone --algorithm blake2bp --hidden --keep-all-tagged, even though there weren't any tagged.

Looking through the resulting script, nothing looked off.

**Comment by SeeSpotRun** [comment] 2018-01-19 00:25
Running `sudo rmlint -T df --config=sh:handler=clone --algorithm blake2bp --hidden --keep-all-tagged` shouldn't generate any new files other than `rmlint.sh` and `rmlint.json`.  It may however chew up a fair bit of RAM and could then eat into swap.  If you had swap configured as a swap file on your btrfs volume then that could cause the issue.

On the other hand, `btrfs` is notoriously poorly behaved when it starts to run out of space.  I suggest running a btrfs balance; Marc Merlins has a [good article](http://marc.merlins.org/perso/btrfs/post_2014-05-04_Fixing-Btrfs-Filesystem-Full-Problems.html) on this.

**Comment by SeeSpotRun** [comment] 2018-01-19 00:33
> eventually claiming to be able to free up 886GB of data on a 1TB volume. As far as I know, the amount of space freed shouldn't exceed 50% of the maximum capacity.

It's possible with reflinks and/or snapshots.  If you had (say) 10 nearly-identical snapshots of the same subvolume then `rmlint` will identify most of the files in the snapshots as duplicates.  These get counted towards potential space that can be freed up.  But in reality you probably don't free much up because the identical snapshotted files are already reflinks of each other.

You might want to consider whether you want `rmlint` to search for duplicates between snapshots; if you know they are already reflinks then you can save time and RAM by excluding them from the search tree.

**Comment by nstgc** [comment] 2018-01-19 01:12
I don't have a swap file, and I regularly balance my volumes. Even then all indicators showed that it wasn't a balancing issue.

**Comment by nstgc** [comment] 2018-01-19 01:15
I went ahead and ran a balance anyway. After deleting 50GB worth of games (lots of small files) and 5 sets of snap shots, I only needed to balance 11 out of 356 chunks. By the way, the output of rmlint --verion:

> ersion 2.6.1 compiled: Jun 21 2017 at [09:16:37] "Penetrating Pineapple" (rev unknown)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.


>

**Comment by SeeSpotRun** [comment] 2018-01-19 01:41
Curious.

None of the [btrfs Gotcha](https://btrfs.wiki.kernel.org/index.php/Gotchas) in play here?

Can you try generating a few similar-sized (to `rmlint.[sh|json`]) text files; that should confirm that it's not an issue with the underlying filesystem?

If that doesn't cause issues, and if `rmlint` is still reproducible causing a problem then that's quite odd.  Could you try compiling the [latest develop branch](https://github.com/sahib/rmlint/tree/develop) from source and try again?

**Comment by nstgc** [comment] 2018-01-19 01:50
No. I read through the Gtochas just now. I copied over All of Final Fantasy X/X-2 remastered from my laptop to my desktop over SSH just now. No issues. It's about 40GB.

I'll try again again tomorrow with my Arch's rmlint. If that fails again, I'll try compiling it myself.

**Comment by nstgc** [comment] 2018-02-09 23:31
I tried this again with similar result. This time I was more conservative, and only ran rmlint on a subvolume. I also ran `btrfs file -du -s` before and after on the entire volume. I also ran a balance (-musage and -dusage at 50%) before hand.

```
sudo rmlint -T df --config=sh:handler=clone --algorithm blake2bp --hidden
==> Note: Please use the saved script below for removal, not the above output.
==> In total 461465 files, whereof 167504 are duplicates in 27528 groups.
==> This equals 66.82 GB of duplicates which could be removed.
==> Scanning took in total 7m 16.875s. Is that good enough?
```

```
sudo btrfs fi du -s /btrfs/raid0
     Total   Exclusive  Set shared  Filename
   5.22TiB    89.65GiB   902.22GiB  /btrfs/raid0
```

```
sudo btrfs fi du -s /btrfs/raid0
     Total   Exclusive  Set shared  Filename
   5.22TiB   153.97GiB   838.04GiB  /btrfs/raid0
```

So it looks like merely running rmlint is breaking existing links. Note, this is before I run the actual script.

**Comment by nstgc** [comment] 2018-02-10 00:27
I ran `btrfs fi du -s` again after executing the script and it returned the same thing. I than ran a balance even though it shouldn't have anything to do with it (indeed 0 chunks were moved). Again, no change. I just wanted to add this extra bit of information. I haven't tried compiling it from the development branch yet.

**Comment by Cebtenzzre** [comment] 2019-09-10 18:59
@nstgc I know this is an old issue, but it is still open.

Is/was this volume mounted with `noatime`?  If not, simply reading a lot of files (e.g., by running rmlint) can increase space usage and decrease metadata sharing, because atime updates trigger copy-on-write.  `relatime` (the default) doesn't help, because it will still update a file's atime if it is more than one day old.

[This LWN article](https://lwn.net/Articles/499293/) explains the problem with atime on btrfs in more detail.

**Comment by nstgc** [comment] 2019-09-11 02:45
Sorry for not following up earlier. I just really didn't feel like compiling this just to troubleshoot (I'm a bad Linux user).

The following is taken from `mount |grep raid0`

    /dev/bcache1 on /btrfs/raid0 type btrfs (rw,relatime,ssd,space_cache,subvolid=5,subvol=/)

So, that's a yes! Thanks for pointing this out.

**Comment by sahib** [comment] 2020-01-13 20:44
Closing since this does not seem to be a ``rmlint`` issue. Please re-open if there's new info.

**Closed by sahib** 2020-01-13 20:44 UTC
