### ISSUE TITLE
Can not use --gui option

### ISSUE THREAD

**Issue by JairoAlonso25** [sahib/rmlint#167] opened 2016-01-30 03:35 UTC
$ rmlint --gui
/usr/bin/python3: No module named shredder

Distro: Ubuntu 15.10

**Comment by SeeSpotRun** [comment] 2016-01-30 04:02
What is the output of:

```sudo scons DEBUG=1 -j4 --prefix=/usr install```

**Comment by albertnet** [comment] 2016-01-30 05:33
Hi, I have the same issue on Ubuntu 15.10.
My output is:

```
$ sudo scons DEBUG=1 -j4 --prefix=/usr install
[sudo] password : 
scons: Reading SConscript files ...
Checking whether the C compiler works... (cached) yes
Checking for git revision... (cached) 0872a68
Checking for pkg-config... (cached) yes
Checking for glib-2.0 >= 2.32... (cached) yes
Checking for gio-unix-2.0... (cached) yes
Checking for blkid... (cached) yes
Checking for json-glib-1.0... (cached) yes
Checking for -std=c11 support...(cached) yes
Checking whether blkid_devno_to_wholedisk is declared... (cached) yes
Checking for existence of /sys/block... (cached) yes
Checking for C header file libelf.h... (cached) yes
Checking for C library libelf... (cached) yes
Checking for C type struct fiemap... (cached) yes
Checking for C function getxattr()... (cached) yes
Checking for C function setxattr()... (cached) yes
Checking for C function removexattr()... (cached) yes
Checking size of off_t ... (cached) yes
Checking for C function stat64()... (cached) yes
Checking whether G_CHECKSUM_SHA512 is declared... (cached) yes
Checking for C header file locale.h... (cached) yes
Checking for C header file linux/limits.h... (cached) yes
Checking whether posix_fadvise is declared... (cached) yes
Checking for C header file linux/btrfs.h... (cached) yes
Checking for C header file sys/utsname.h... (cached) yes
Building rmlint
scons: done reading SConscript files.
scons: Building targets ...
build_config_template(["lib/config.h"], ["lib/config.h.in"])
build_python_formatter(["lib/formats/py.c"], ["lib/formats/py.c.in"])
build_sh_formatter(["lib/formats/sh.c"], ["lib/formats/sh.c.in"])
msgfmt po/de.po -o po/de.mo
msgfmt po/fr.po -o po/fr.mo
cd gui && python3 setup.py install --prefix /usr --record .files.txt
running install
==> Compiling resource bundle
==> Using existing. Lucky boy.
running build
running build_py
running install_lib
running install_data
running install_egg_info
Removing /usr/lib/python3.4/site-packages/Shredder-2.4.2.Myopic.Micrathene-py3.4.egg-info
Writing /usr/lib/python3.4/site-packages/Shredder-2.4.2.Myopic.Micrathene-py3.4.egg-info
writing list of installed files to '.files.txt'
==> Compiling GLib Schema files
==> OK!
scons: done building targets.
```

I tried to google it to no avail. Thank you in advance for your time.

**Comment by SeeSpotRun** [comment] 2016-01-30 06:28
I think it's a duplicate of https://github.com/sahib/rmlint/issues/153#issuecomment-145341600

Try:

``` $ export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/ ```

**Comment by albertnet** [comment] 2016-01-30 06:31
Hi @SeeSpotRun 

I guess you're right, it's a duplicate however it's already closed and although I tried that solution already it didn't solve it, therefore I am reaching out to see if there's a way to solve it.

**Comment by SeeSpotRun** [comment] 2016-01-30 22:01
I'm not real strong on python environment issues but I'll install Ubuntu 15.10 and have a play with it...

**Comment by SeeSpotRun** [comment] 2016-01-31 08:41
Ok looks like a problem with the Ubuntu version of python3-gi.  With the PYTHONPATH workaround I get past the ```No module named shredder``` error but get a new error ```cannot import name Polkit```

**Comment by arturpriz** [comment] 2016-01-31 09:29
Ubuntu 15.04
Completely agree with albertnet. Nothing helps.
Stuck on - error cannot import name Polkit

**Comment by sahib** [comment] 2016-01-31 15:58
There is also issue https://github.com/sahib/rmlint/issues/159.

Basically, that's nothing ``rmlint`` can do much about. See the other issue, but as long Ubuntu decides to break python packages without a good reason I can't do much against it.

The only viable solution is for someone to package ``rmlint-shredder`` for Ubuntu for the greater good.
But until now there were only attempts, but no full package that got into the repos. We need to rely
on community efforts here, since we're no Ubuntu users and are busy enough without maintaining packages.
See Issue https://github.com/sahib/rmlint/issues/143.

For the polkit error, you problaby need to install the ``gir1.2-polkit-1.0`` package:

```bash
$ sudo apt-get install gir1.2-polkit-1.0
```

**Comment by JairoAlonso25** [comment] 2016-01-31 16:20
@sahib Thanks, your solutions fix my problem with rmlint --gui. This can be closed

**Comment by albertnet** [comment] 2016-01-31 22:33
I'm eager to report the same as @JairoAlonso25 , I'm gonna run the previous commands to see if it works for me. I'll let you know what my results are in a few moments.

**Comment by albertnet** [comment] 2016-01-31 22:54
Definitely working!!!
I'm glad to say this worked perfectly. Just for those needing a bit of history I'll describe, to the best of my knowledge my experience.
Started by running the commands perfectly described in: [http://rmlint.readthedocs.org/en/latest/install.html](url)
After finding some problems I realized I needed to update and upgrade my Ubuntu 15.10 completely until I would get: `$ sudo apt-get upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`
After that, start again by running every command in the installation webpage and everything should be perfect, then run `rmlint --gui`and the issues started. 
Once I ran it from command line I knew it was just matter of expert hands such as @SeeSpotRun and @sahib  to get the gui running.
I ran the command `export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/` as instructed by @SeeSpotRun  and then my terminal showed something else but still no gui.
Then as per @sahib directions I installed `sudo apt-get install gir1.2-polkit-1.0`
The again run command `rmlint --gui` and voila! It's working beautifully and I can see the glorious interface in all it's graphical glory before my non-command-line eyes!

Thank you very much for the time and efforts to everyone involved in this issue and that only shows that the linux community is the best thing the world of computers could ever happen to.
This definitely can be closed!

**Comment by albertnet** [comment] 2016-02-01 07:51
Ok, maybe not to be closed yet.
I just tried to run it again and the dreaded output showed again: 
rmlint --gui
/usr/bin/python3: No module named shredder
I re-runned `export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/` and then again `rmlint --gui` and its working again.
Am I to assume that `export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/` is not maintained? I guess that is the obvious answer. I tried locking the app to the Unity launcher but it won't launch, so, open the terminal again and run the command and works again. Now, Is there a way to make it permanent?
Thank you.

**Comment by albertnet** [comment] 2016-02-01 09:00
So, to make it automated I wrote a simple script and now I run it as a regular application link. Opened a new empty document with the following text:

[Desktop Entry]
Version=1.0
Name=rmlint_Graphic        
Comment=Tries to run rmlint with GUI attributes
Exec=gnome-terminal -x bash -c "export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/; rmlint --gui"
Icon=/home/WHOEVER/Pictures/shredder.png
Terminal=true
Type=Application
Categories=Application;

Saved it as a .desktop file and allowed to execute it as a program.This solves my issue but I know it's not the most fancy solution. I'm open to suggestions, comments and criticism (the good one, tho XD).
Thank you!

**Comment by sahib** [comment] 2016-02-01 12:42
The proper solution is probably putting this either in ``.bashrc``, ``.bash_profile`` or even ``/etc/profile``:

```bash
# Other distributions already setup this correctly:
export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/
```

Logging out and in again might be necessary for the effects to take place persistently.
We already have a ``shredder.desktop`` file by the way.

**Comment by albertnet** [comment] 2016-02-01 18:29
I just found your  `shredder.desktop` and well, I didn't know but I guess I didn't do it so bad, right?
I'm going to try the solutions before mentioned and I'll post my results.
Thank you @sahib

**Comment by sahib** [comment] 2016-02-04 11:53
Closing now, since nothing new happened. If the same problem occurs again, feel free to re-open.

**Closed by sahib** 2016-02-04 11:53 UTC
Labels: Fix needed, Help Wanted!
