### ISSUE TITLE
Shredder does not include manually toggled files

### ISSUE THREAD

**Issue by megitu** [sahib/rmlint#385] opened 2019-10-26 09:43 UTC
After manually toggling individual files and running "Render script from Selected", these toggled files are not correctly marked in the generated script.
The generated script is always the same as in the case of "Render script from All" (and these manually toggled files are not correctly marked on the lines: "original_cmd" and "remove_cmd").

**Comment by sahib** [comment] 2019-10-26 09:47
Hello @megitu,

What version are you using? This is probably a duplicate of #375. Please check if compiling from the  ``develop`` branch fixes it for you.

**Comment by megitu** [comment] 2019-10-26 10:03
I am using 2.9.0 under Manjaro Linux.
[#375](https://github.com/sahib/rmlint/issues/375), as I understand it, is a similar case and much more completed but probably not the same.
I will try to use the develop branch fixes (if I can use it).

**Comment by ecdlguy** [comment] 2019-10-26 20:06
Hi, thank you for writing this issue... It saved me from deleting some dupes at the wrong location. 
I've noticed that toggling files in shredder is never rendered correctly in the generated script.
I'm using version version 2.8.0 "Maidenly Moose" (rev 3), though.

**Comment by HaleTom** [comment] 2019-11-04 07:01
+1 for keyboard shortcuts for both `Toggle selected` and `Toggle all`.

With a lot of dupes, it's RSI-inducing to use the moose for this :)

**Comment by s-rogonov** [comment] 2021-01-14 12:01
also it seems like I f****d up a looooot of my files =/
sad to be me

**Comment by SeeSpotRun** [comment] 2021-03-22 05:17
Hi all, sorry for very tardy buy-in to this.

Yes I can reproduce the issue as follows:
* Scan a folder using `rmlint --gui`
* Manually toggle files to tag a different file as original.
* Generate `rmlint.sh`,
* Desired result: the manually tagging of originals is reflected in the shell output script.
* Observed result: the manually tagging of originals is not reflected in the shell output script.

@sahib I can't find anything in the `--replay` logic that preserves the originals status from the json cache.  I went ahead and coded #482 to do this, but would prefer to have your feedback before merging it, in case I'm missing something.

**Comment by SeeSpotRun** [comment] 2021-05-20 02:43
This should be addressed as of https://github.com/sahib/rmlint/commit/b94e5aca2d54ca3240e5d94c342a2686bb6ab16b which has been merged into `develop` branch

Use option `--keep-cached-originals` ("For --replay runs, preserve any originals in json cache")

**Closed by SeeSpotRun** 2021-05-20 02:43 UTC
