### ISSUE TITLE
'O_LARGEFILE' error on compilation (OSX)

### ISSUE THREAD

**Issue by l2** [sahib/rmlint#139] opened 2015-06-14 14:42 UTC
I am trying to compile rmlint on OSX 10.10.3 and I have the following error message:

**lib/utilities.h:69:13: error: use of undeclared identifier 'O_LARGEFILE'**

Do you know how can I resolve it?

**Comment by sahib** [comment] 2015-06-14 15:16
Hi, please try again after a pull.

From what I can see O_LARGEFILE does not seem to be needed on OSX...

**Comment by l2** [comment] 2015-06-14 16:46
Thanks 

I don't have this error but a new one :-):

**lib/file.c:67:26: error: no member named 'st_mtim' in 'struct stat64'**

**Comment by sahib** [comment] 2015-06-14 17:51
That error is because apple gave different names to some struct members (for no apparent reasons).

Please try again. The warnings are probably not important.

**Comment by l2** [comment] 2015-06-14 19:45
Thanks but now I have the following errors

> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/stat.h:390:5: note: 'lstat64' has been explicitly marked deprecated here
> int     lstat64(const char *, struct stat64 *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5,__MAC_10_6,__IPHONE_NA,__IPHONE_NA);
>         ^
> In file included from lib/replay.c:28:
> In file included from lib/session.h:38:
> In file included from lib/treemerge.h:30:
> In file included from lib/file.h:33:
> In file included from lib/cfg.h:32:
> lib/utilities.h:99:12: warning: implicit declaration of function 'preadv' is invalid in C99 [-Wimplicit-> function-declaration]
>     return preadv(fd, iov, iovcnt, offset);
>            ^
> lib/replay.c:52:5: error: unknown type name 'JsonParser'
>     JsonParser *parser;
>     ^
> lib/replay.c:55:5: error: unknown type name 'JsonArray'
>     JsonArray *root;
>     ^
> lib/replay.c:71:9: warning: implicit declaration of function 'g_object_unref' is invalid in C99 [-Wimplicit-> function-declaration]
>        g_object_unref(polly->parser);
>         ^
> lib/replay.c:81:21: warning: implicit declaration of function 'json_parser_new' is invalid in C99 [-Wimplicit-function-declaration]
 >    polly->parser = json_parser_new();
>                     ^
> lib/replay.c:94:9: warning: implicit declaration of function 'json_parser_load_from_file' is invalid in C99 [-Wimplicit-function-declaration]
>     if(!json_parser_load_from_file(polly->parser, json_path, error)) {
>         ^
> lib/replay.c:98:5: error: use of undeclared identifier 'JsonNode'
>     JsonNode *root = json_parser_get_root(polly->parser);
>     ^
> lib/replay.c:98:15: error: use of undeclared identifier 'root'
>     JsonNode *root = json_parser_get_root(polly->parser);
>               ^
> lib/replay.c:98:22: warning: implicit declaration of function 'json_parser_get_root' is invalid in C99 [-Wimplicit-function-declaration]
>     JsonNode *root = json_parser_get_root(polly->parser);
>                      ^
> lib/replay.c:99:8: warning: implicit declaration of function 'JSON_NODE_TYPE' is invalid in C99 [-Wimplicit-function-declaration]
>     if(JSON_NODE_TYPE(root) != JSON_NODE_ARRAY) {
>        ^
> lib/replay.c:99:23: error: use of undeclared identifier 'root'
>     if(JSON_NODE_TYPE(root) != JSON_NODE_ARRAY) {
>                       ^
> lib/replay.c:99:32: error: use of undeclared identifier 'JSON_NODE_ARRAY'; did you mean 'JSON_NODE_TYPE'?
>     if(JSON_NODE_TYPE(root) != JSON_NODE_ARRAY) {
>                                ^~~~~~~~~~~~~~~
>                                JSON_NODE_TYPE
> lib/replay.c:99:8: note: 'JSON_NODE_TYPE' declared here
>     if(JSON_NODE_TYPE(root) != JSON_NODE_ARRAY) {
>        ^
> lib/replay.c:104:19: warning: implicit declaration of function 'json_node_get_array' is invalid in C99 [-Wimplicit-function-declaration]
>     polly->root = json_node_get_array(root);
>                   ^
> lib/replay.c:104:39: error: use of undeclared identifier 'root'
>     polly->root = json_node_get_array(root);
>                                       ^
> lib/replay.c:113:28: warning: implicit declaration of function 'json_array_get_length' is invalid in C99 [-Wimplicit-function-declaration]
>     return (polly->index < json_array_get_length(polly->root));
>                            ^
> lib/replay.c:125:5: error: use of undeclared identifier 'JsonObject'
>     JsonObject *object = json_array_get_object_element(polly->root, polly->index);
>     ^
> lib/replay.c:125:17: error: use of undeclared identifier 'object'
>     JsonObject *object = json_array_get_object_element(polly->root, polly->index);
>                 ^
> lib/replay.c:125:26: warning: implicit declaration of function 'json_array_get_object_element' is invalid in C99 [-Wimplicit-function-declaration]
>     JsonObject *object = json_array_get_object_element(polly->root, polly->index);
>                          ^
> lib/replay.c:131:5: error: use of undeclared identifier 'JsonNode'
>     JsonNode *path_node = json_object_get_member(object, "path");
>     ^
> lib/replay.c:131:15: error: use of undeclared identifier 'path_node'
 >    JsonNode *path_node = json_object_get_member(object, "path");
>               ^
> lib/replay.c:131:27: warning: implicit declaration of function 'json_object_get_member' is invalid in C99 [-Wimplicit-function-declaration]
>     JsonNode *path_node = json_object_get_member(object, "path");
>                           ^
> lib/replay.c:131:50: error: use of undeclared identifier 'object'
>     JsonNode *path_node = json_object_get_member(object, "path");
>                                                  ^
> lib/replay.c:132:8: error: use of undeclared identifier 'path_node'
>     if(path_node == NULL) {
>        ^
> lib/replay.c:136:12: warning: implicit declaration of function 'json_node_get_string' is invalid in C99 [-Wimplicit-function-declaration]
>     path = json_node_get_string(path_node);
>            ^
> lib/replay.c:136:33: error: use of undeclared identifier 'path_node'
>     path = json_node_get_string(path_node);
>                                 ^
> lib/replay.c:141:9: warning: implicit declaration of function 'json_object_get_string_member' is invalid in C99 [-Wimplicit-function-declaration]
>         json_object_get_string_member(object, "type")
>         ^
> lib/replay.c:141:39: error: use of undeclared identifier 'object'
>         json_object_get_string_member(object, "type")
>                                       ^
> lib/replay.c:147:43: error: use of undeclared identifier 'object'
>             json_object_get_string_member(object, "type")
>                                           ^
> lib/config.h:125:20: note: expanded from macro 'rm_log_warning_line'
>     rm_log_warning(__VA_ARGS__); \
>                    ^
> lib/config.h:62:42: note: expanded from macro 'rm_log_warning'
>     g_log("rmlint", G_LOG_LEVEL_WARNING, __VA_ARGS__)
>                                          ^
> lib/replay.c:167:5: error: use of undeclared identifier 'JsonNode'
>     JsonNode *mtime_node = json_object_get_member(object, "mtime");
>     ^
> lib/replay.c:167:15: error: use of undeclared identifier 'mtime_node'
>     JsonNode *mtime_node = json_object_get_member(object, "mtime");
>               ^
> lib/replay.c:167:51: error: use of undeclared identifier 'object'
>     JsonNode *mtime_node = json_object_get_member(object, "mtime");
>                                                   ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 14 warnings and 20 errors generated.
> scons: *** [lib/replay.o] Error 1

**Comment by sahib** [comment] 2015-06-14 21:38
Ah, you're using ``develop``. Please do a pull and try again.
There were missing #ifdefs for a work-in-progress feature.

**Comment by l2** [comment] 2015-06-14 21:46
If you prefer I can stay on the master branch. 

On the develop branch I have now only these several errors :-)
> lib/shredder.c:1520:57: error: use of undeclared identifier
>       'POSIX_FADV_SEQUENTIAL'
>         posix_fadvise(fd, file->seek_offset, readahead, SHRED_FADVISE_FLAGS);
>                                                         ^
> lib/shredder.c:241:10: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>     (0 | POSIX_FADV_SEQUENTIAL /* Read from 0 to file-size    */ \
>          ^
> lib/shredder.c:1520:57: error: use of undeclared identifier
>       'POSIX_FADV_WILLNEED'
> lib/shredder.c:242:8: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>      | POSIX_FADV_WILLNEED     /* Tell the kernel to readhead */ \
>        ^
> lib/shredder.c:1520:57: error: use of undeclared identifier 'POSIX_FADV_NOREUSE'
> lib/shredder.c:243:8: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>      | POSIX_FADV_NOREUSE      /* We will not reuse old data  */ \
>        ^
> lib/shredder.c:1597:65: error: use of undeclared identifier
>       'POSIX_FADV_SEQUENTIAL'
>     posix_fadvise(fileno(fd), file->seek_offset, bytes_to_read, SHRED_FA...
>                                                                 ^
> lib/shredder.c:241:10: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>     (0 | POSIX_FADV_SEQUENTIAL /* Read from 0 to file-size    */ \
>          ^
> lib/shredder.c:1597:65: error: use of undeclared identifier
>       'POSIX_FADV_WILLNEED'
> lib/shredder.c:242:8: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>      | POSIX_FADV_WILLNEED     /* Tell the kernel to readhead */ \
>        ^
> lib/shredder.c:1597:65: error: use of undeclared identifier 'POSIX_FADV_NOREUSE'
> lib/shredder.c:243:8: note: expanded from macro 'SHRED_FADVISE_FLAGS'
>      | POSIX_FADV_NOREUSE      /* We will not reuse old data  */ \

**Comment by sahib** [comment] 2015-06-14 21:50
No, it's okay to stay on `develop`. The chance of breakage is just higher there.
I think I fixed that last one, so let's continue the dance.

`rmlint` doesn't seem to have got much attention on OSX since some time.

**Comment by l2** [comment] 2015-06-14 21:54
Errors:
> lib/utilities.c:1225:7: error: conflicting types for 'rm_offset_get_from_fd'
> RmOff rm_offset_get_from_fd(_U int fd, _U RmOff file_offset) {
>       ^
> lib/utilities.h:323:7: note: previous declaration is here
> RmOff rm_offset_get_from_fd(int fd, RmOff file_offset, RmOff *file_offset_next);
>       ^
> lib/utilities.c:1229:7: error: conflicting types for 'rm_offset_get_from_path'
> RmOff rm_offset_get_from_path(_U const char *path, _U RmOff file_offset) {
>       ^
> lib/utilities.h:330:7: note: previous declaration is here
> RmOff rm_offset_get_from_path(const char *path, RmOff file_offset, RmOf...
>       ^
> lib/utilities.c:1230:13: error: expected ';' after return statement
>     return 0
>             ^
>             ;
> 3 warnings and 3 errors generated.

**Comment by sahib** [comment] 2015-06-14 21:59
Another one bites the dust.

**Comment by l2** [comment] 2015-06-14 22:01
If you prefer you can create a chat on gitter associated to the repository for discussing in live.

> lib/xattr.c:97:86: error: too few arguments to function call, expected 6, have 5
>   ...setxattr(file_path, key, value, value_size, 0));
>      ~~~~~~~~                                     ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/xattr.h:65:1: note:
>       'setxattr' declared here
> int setxattr(const char *path, const char *name, const void *value, size...
> ^
> lib/xattr.c:105:87: error: too few arguments to function call, expected 6, have
>       4
>   ...getxattr(file_path, key, out_value, value_size));
>      ~~~~~~~~                                      ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/xattr.h:61:1: note:
>       'getxattr' declared here
> ssize_t getxattr(const char *path, const char *name, void *value, size_...
> ^
> lib/xattr.c:110:70: error: too few arguments to function call, expected 3, have
>       2
>     return rm_xattr_is_fail("removexattr", removexattr(file_path, key));
>                                            ~~~~~~~~~~~               ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/xattr.h:69:1: note:
>       'removexattr' declared here
> int removexattr(const char *path, const char *name, int options);
> ^
> 3 warnings and 3 errors generated.

**Comment by sahib** [comment] 2015-06-14 22:03
There is ``#rmlint`` on ``irc.freenode.net``.

**Comment by sahib** [comment] 2015-06-14 23:24
As of d4f84575bf03d778706ca57f9ae0decf24e0577c `rmlint` should compile on OSX without major problems:

http://pastebin.com/AAKnVpqs

**Comment by dubiousjim** [comment] 2015-08-27 17:06
I had to make this change to that commit to get it to build on my system. (Mac OS X 10.10.5 with MacPorts). Also I had to specify CC=clang. Using the system gcc or clang seemed to work ok, and also the macports clang-3.6, but using the macports gcc49 didn't work. Here's the change I made:

    diff --git a/lib/utilities.c b/lib/utilities.c
    index e1895d7..cf0ef4e 100644
    --- a/lib/utilities.c
    +++ b/lib/utilities.c
    @@ -390,7 +390,7 @@ void rm_json_cache_parse_entry(_U JsonArray *array, _U guint index,
                 return;
             }
    
    -        if(json_node_get_int(mtime_node) < stat_buf.st_mtim.tv_sec) {
    +        if(json_node_get_int(mtime_node) < stat_buf.st_mtimespec.tv_sec) {
                 /* file is newer than stored checksum */
                 return;
             }

**Comment by sahib** [comment] 2015-08-27 17:51
Hi @dubiousjim,

thanks for the report.
I applied the proper fix at 8005243451c08e3443934c6f7b7b560b4ba9c2ca. 
Can you verify it works?

**Comment by dubiousjim** [comment] 2015-08-27 18:02
That doesn't build, for a different reason.

```
Compiling ==> lib/hasher.c
lib/hasher.c:183:5: warning: implicit declaration of function 'posix_fadvise' is invalid in C99 [-Wimplicit-function-declaration]
    posix_fadvise(fileno(fd), start_offset, bytes_to_read, HASHER_FADVISE_FLAGS);
    ^
1 warning generated.
...
Linking Program ==> rmhash
ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture x86_64:
  "_posix_fadvise", referenced from:
      _rm_hasher_task_hash in librmlint.a(hasher.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [rmhash] Error 1
scons: building terminated because of errors.
```

I also had that problem trying to build the `master` branch; but not with trying to build `d4f8457`.

**Comment by dubiousjim** [comment] 2015-08-27 18:33
Here's what I did to get the commit `8005243` to compile: I added this line to the top of `lib/hasher.c`:

    #define posix_fadvise(fd, offset, len, advice) (0)

That builds and starts to run fine. But then when I invoke it using the same line as above, I get an error --- a different error than before. Now I get:

    ERROR:lib/checksum.c:683:rm_digest_equal: assertion failed: (a->type == b->type)

**Comment by sahib** [comment] 2015-08-27 19:07
There as some code refactoring between d4f8457 and now. Sadly, we managed to get some compile stops for MacOSX back.

Please try again with the ```develop``` branch.

**Comment by dubiousjim** [comment] 2015-08-27 20:21
Just pulled and built `develop`, the current commit is:

```
$ git describe
v2.2.0-382-gcd538b1
```
This builds without any difficulties. I had to do some massaging to get it to install, since I said `--prefix=$HOME`, on all three invocations of `scons`, but it nonetheless wants to install stuff in:

```
/usr/share/applications
/usr/share/glib-2.0
/usr/share/icons
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/
```

The last is where the MacPorts install of `python34` is located. These look like they're all for the Shredder gui app, which I don't want but don't know how to disable the installation of. So I just let it install in these spots but then deleted that stuff. It would be nice if the build logic permitted installation without root privileges, and also permitted disabling the gui. Perhaps it already does, and I just don't know the right invocation.

In any case, this version of `rmlist` builds fine, but running it on two small test folders with duplicate files in them gives me the same error it did before:

    ERROR:lib/checksum.c:638:rm_digest_needs_steal: code should not be reached

**Comment by sahib** [comment] 2015-08-28 10:10
Hi @dubiousjim, 

those file are indeed all owned by Shredder. 
It's build process needs still work, but you can disable it via ```--without-gui```. 

That other problem is a bit weird and hard to track down from the message. It is probably related to @SeeSpotRun's refactoring. Could you give us a ``gdb`` backtrace?
(``gdb --ex run -ex bt --args rmlint -vvv [your_options]``)

**Comment by dubiousjim** [comment] 2015-08-28 12:06
You'll need to give me different build instructions. I can see that I didn't build with debugging symbols, but I should still get a backtrace, yet I'm not. Here's what I've done:

```
$ git describe
v2.2.0-382-gcd538b1

$ CC=clang scons config --prefix=$HOME --without-gui && CC=clang scons --prefix=$HOME --without-gui && CC=clang scons --prefix=$HOME install --without-gui
```

I couldn't figure out where the --without-gui was needed; just putting it on the config step wasn't enough.

```
$ mkdir testa testb && echo "john" > testa/john && echo "john" > testb/john
$ echo "john" > testa/jacques
$ echo "mary" > testa/mary && ln testa/mary testb/
$ rmlint -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T "none,df,dd"  testb // testa

ERROR:lib/checksum.c:638:rm_digest_needs_steal: code should not be reached
```

At this point, terminal is a bit screwed up (no cursor), so:

```
$ reset
$ gdb --ex run -ex bt --args rmlint -vvv -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T "none,df,dd"  testb // testa

GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rmlint...(no debugging symbols found)...done.
Starting program: /Users/jim/Downloads/rmlint/rmlint -vvv -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T none,df,dd testb // testa
Unable to find Mach task port for process-id 98739: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
No stack.
(gdb) q
```

**Comment by sahib** [comment] 2015-08-28 12:43
Sorry, forgot to tell you that you need to build with "scons DEBUG=1". 
With this, you'll have a ``rmlint`` binary in the current directory.
The backtrace should just work afterwards.

The ``--without-gui`` part should happen at the ``install`` stage (which invokes the build stage too).
So, you could use:

``CC=clang scons install --prefix=$HOME --without-gui ``

Fyi: The ``config`` step is not doing anything, except showing you the current configuration. That's not related to a ``./configure``.

**Comment by dubiousjim** [comment] 2015-08-28 12:53
Thanks. There's still some issue with using gdb. I'm guessing it's Mac-related. Witness (after cleaning my git working directory of the old build):

```
$ CC=clang scons install DEBUG=1 --prefix=$HOME --without-gui
$ rmlint -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T "none,df,dd"  testb // testa
ERROR:lib/checksum.c:638:rm_digest_needs_steal: code should not be reached
$ reset
$ gdb --ex run -ex bt --args rmlint -vvv -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T "none,df,dd"  testb // testa
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rmlint...done.
Starting program: /Users/jim/Downloads/rmlint/rmlint -vvv -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T none,df,dd testb // testa
Unable to find Mach task port for process-id 52928: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
No stack.
(gdb) run
Starting program: /Users/jim/Downloads/rmlint/rmlint -vvv -b -o sh:linkdupes.sh -c sh:hardlink -S mD -k -m -g -T none,df,dd testb // testa
Unable to find Mach task port for process-id 52937: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
(gdb) q
```

**Comment by sahib** [comment] 2015-08-28 13:03
Yes, probably some weird mac-ness (think different! :smirk:).

Maybe using ``valgrind`` makes more sense here:

``valgrind --leak-check=no rmlint -vvv [your_options]``

**Comment by dubiousjim** [comment] 2015-08-28 13:14
Yeah, I much prefer using my linux machines, especially when developing. But I wanted to run rmlint on the Mac. I'm not a fan of this package manager I'm using for the Mac either, but it's the best of a bad lot, plus I'm already invested in it. Unfortunately, the package manager chokes when I try to install valgrind with the version of gcc I've got installed. Now I could start mixing and matching different compiler packages (would have to build each version) and versions of valgrind, but I don't know in advance what would work and give us useful results, plus I don't really have the time to play with that atm. For my immediate de-duping purposes, I hacked together some scripts to post-process output from `duff`. If you get any other ideas for things I could try to help get rmlint working on the Mac, let me know. Seems like it'd be a great tool. I'll be glad to use it on my linux machines.

**Comment by sahib** [comment] 2015-08-28 13:17
Would be glad to have that resolved. 
Maybe it's best to wait for @SeeSpotRun if he has an immediate idea from where this assertion would come from.

**Comment by SeeSpotRun** [comment] 2015-08-28 20:43
The assertion (a->type==b->type) in rm_digest_equal(a, b) is checked before comparing two digests to see if they are equal.  As far as I'm aware, there is no scenario where rmlint should be comparing  two digest checksums of different types.

I ran your testcase and got the same error (ERROR:lib/checksum.c:638:rm_digest_needs_steal: code should not be reached).  It looks like there's a problem with file digests being discarded before treemerge is finished.  I should have a fix soon.

**Comment by sahib** [comment] 2015-08-28 21:15
D'oh. Shame on me, I can reproduce it too, sorry for my laziness.
Thanks to Spot for the fix.

@dubiousjim: Can you verify the assertion vanished?

**Comment by dubiousjim** [comment] 2015-08-28 22:23
Can verify that with: `v2.2.0-391-g39e0822`, it builds and runs my test case without any problems. I guess we can close this issue. If I encounter other troubles downstream, I'll open a new issue where they belong.

I guess I don't understand the `-o sh:filename` option; I thought it would then write output to `filename`, but it just uses `rmlint.json` and `rmlint.sh`, and my `filename` is touched but is empty.

**Comment by sahib** [comment] 2015-08-28 23:38
This is not strictly a bug, but a confusing feature to be honest.
``-g`` sets a pre-defined set of formatters and paths to write out (progressbar, summary, rmlint.sh and rmlint.json). When specified after ``-o sh:filename`` it will overwrite it. Specifying it after will write filename, rmlint.sh and rmlint.json.  This was originally added to make sure the user finds some output on the disk. That thought did not include you...

A workaround would be to use ``-o progressbar`` instead of ``-g``. 
I will make ``-g`` a bit more clever tomorrow and make it check if there is a another sh script/json file on the commandline.

**Comment by dubiousjim** [comment] 2015-08-28 23:52
Oh ok, thanks, I understand now.

**Comment by sahib** [comment] 2015-08-29 11:13
Should be less surprising as of 90d09111b5ea1f77aec3f329c068e140ee73b02c.

**Closed by sahib** 2015-08-29 11:13 UTC
Labels: Bug, sahib-broke-it
