### ISSUE TITLE
generated rmlint.sh script dry-run (-n) is incompatible with paranoid (-p) for directories

### ISSUE THREAD

**Issue by brianrmurphy** [sahib/rmlint#610] opened 2023-02-09 00:00 UTC
Running the generated script "./rmlint.sh -n -p" runs "rmlint --equal" to compare directories but running "rmlint --equal" overwrites rmlint.sh and rmlint.json.

I think the latter behavior (overwriting rmlint.sh and rmlint.json when you run rmlint --equal) is the real bug, since it contradicts the man page, but the problem shows up here.

**Comment by Cebtenzzre** [comment] 2023-02-09 16:38
This is a duplicate of issue #552.

**Closed by Cebtenzzre** 2023-02-09 16:38 UTC
