### ISSUE TITLE
Bad results running in git-annex directory

### ISSUE THREAD

**Issue by viric** [sahib/rmlint#278] opened 2018-03-10 22:08 UTC
Running rmlint 2.6.1 in a git-annex directory works bad:

```
$ rmlint -f .
....
ERROR: BUG: Number of remaining bytes is 18446744071156496667 (not 0). Please report this.
```

The files in a git-annex directory look like symlinks like this:
```
VID_20170106_152228.mp4 -> ../../../.git/annex/objects/4V/J0/SHA256E-s8161888--bba97442b7a553640c97e9b25f3ebc0a11b04e2929c5595e13791d365976c896.mp4/SHA256E-s8161888--bba97442b7a553640c97e9b25f3ebc0a11b04e2929c5595e13791d365976c896.mp4
```

They may be sometimes broken, sometimes not.

I'm trying to use "rmlint" to find whether I have in my git-annex some files that are in a normal directory: `rmlint -fbk NORMAL // ANNEX` and it doesn't find anything, while the files are there and with the same name (in the annex symlink, of course).

**Comment by SeeSpotRun** [comment] 2018-03-11 05:24
Can you try with the [develop branch](https://github.com/sahib/rmlint/tree/develop) please?  There are a few bugfixes already in there which hopefully address the issue, and if not then you can help us find the remaining bug(s).

You will need to [compile from source](http://rmlint.readthedocs.io/en/latest/install.html)

**Comment by SeeSpotRun** [comment] 2018-06-17 00:34
@sahib Suggest you close this as a probable duplicate of #256

**Comment by sahib** [comment] 2018-06-18 09:08
@SeeSpotRun: Agreed. @viric: Please go to #256 if you want to jump in again.

**Closed by sahib** 2018-06-18 09:08 UTC
