### ISSUE TITLE
Fails to compile in Ubuntu 22.04 vm under lxd with "2.10.1 Ludicrous Lemur' is not valid according to PEP 440"

### ISSUE THREAD

**Issue by Halfwalker** [sahib/rmlint#612] opened 2023-03-03 22:55 UTC
General Ubuntu 22.04/jammy VM running under LXD on a 22.04 box.  `scons config` works fine
```
    Find non-stripped binaries (needs libelf)             : yes
    Optimize using ioctl(FS_IOC_FIEMAP) (needs linux)     : yes
    Support for SHA512 (needs glib >= 2.31)               : yes
    AVX512F and AVX512VL cpu extensions                   : no
    AVX2 cpu extensions                                   : no
    SSE4.1 cpu extensions                                 : no
    SSE2 cpu extensions                                   : no
    Build manpage from docs/rmlint.1.rst                  : yes, using /usr/bin/sphinx-build
    Support for caching checksums in file's xattr         : yes
    Checking for proper support of big files >= 4GB       : yes
        (needs either sizeof(off_t) >= 8 ...)             : yes
        (... or presence of stat64)                       : yes

    Optimize non-rotational disks                         : yes
        (needs libblkid for resolving dev_t to path)      : yes
        (needs gio-unix-2.0)                              : yes

    Enable gettext localization                           : yes
        (needs <locale.h> for compile side support)       : yes
        (needs msgfmt to compile .po files)               : yes

The following constants will be used during the build:

    Version information  : 2.10.1 "Ludicrous Lemur" (rev 58d29ec1)
    Compiler             : gcc
    Install prefix       : None
    Actual prefix        : None
    Verbose building     : no
    Adding debug checks  : no
    Adding debug symbols : no
```
But compiling with `scons --prefix=/usr/local install` fails ...
```
/usr/local/lib/python3.10/dist-packages/setuptools/dist.py:561: UserWarning: The version specified ('2.10.1 Ludicrous Lemur') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
==> Calling glib-compile-resources
/usr/local/lib/python3.10/dist-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: '2.10.1 Ludicrous Lemur'.
        !!


        ###################
        # Invalid version #
        ###################
        '2.10.1 Ludicrous Lemur' is not valid according to PEP 440.

        Please make sure specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.


!!

  warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
Traceback (most recent call last):
  File "/usr/src/rmlint/gui/setup.py", line 90, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/src/rmlint/gui/setup.py", line 40, in run
    super().run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 708, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/install_scripts.py", line 18, in run
    self.run_command("egg_info")
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 220, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2.10.1.Ludicrous.Lemur'
scons: *** [gui/always.install] Error 1
scons: building terminated because of errors.
```

**Comment by Cebtenzzre** [comment] 2023-03-03 23:05
Duplicate of #608

**Closed by Cebtenzzre** 2023-03-03 23:05 UTC
