### ISSUE TITLE
cloning files on BTRFS read-only snapshots doesn't work

### ISSUE THREAD

**Issue by saintger** [sahib/rmlint#195] opened 2016-10-27 15:34 UTC
Trying to deduplicate/clone files which are on BTRFS read-only snapshots, return an error:

```
ERROR: btrfs clone: failed to open dest file.
```

If it helps, duperemove has a special flag ("-A") to manage this situation:
https://github.com/markfasheh/duperemove/blob/master/filerec.c#L405-L434

**Comment by sahib** [comment] 2016-10-29 17:01
I guess you used a command like this?

```bash
$ rmlint -c sh:link subvol/
```

And tried to execute ``rmlint.sh`` afterwards?

```bash
$ ./rmlint.sh
```

If so, what would your expected behaviour be?
If not, which commands did you use exactly?

I see that the error message is not very nice, but, as I understand you, you're suggesting that
this message is silenced and becomes a no-op in case of readonly subvolumes?
(Sorry, hadn't time to look into duperemove yet)

**Comment by SeeSpotRun** [comment] 2016-11-07 03:15
Thanks @saintger for finding this.

It doesn't seem well documented anywhere but here's what I found by trial-and-error and reference to https://github.com/markfasheh/duperemove/commit/fe67b7c5b7222bd2ef54dbd753f170d75e13c45d:
* Read-only snapshots can only be opened read-only (makes sense)
* To clone identical files in btrfs, the target must generally be opened for writing (makes sense)
* However, the BTRFS_IOC_FILE_EXTENT_SAME ioctl will also work with a read-only target if called with elevated priveleges (sounds scary but is reasonable when you think it through).

Branch https://github.com/SeeSpotRun/rmlint/tree/btrfs-clone-readonly should be able to deduplicate read-only snapshots.
Usage for deduping a single file (source and dest must have same data; requires elevated priveleges):
```
$ sudo rmlint --btrfs-clone -r <source> <dest>
```

Usage via rmlint.sh:
```
$ rmlint --config=sh:handler=clone subvolume subvolume_read_only
$ ./rmlint.sh -r   # note: will ask for sudo password
```

**Comment by saintger** [comment] 2016-11-10 14:38
@SeeSpotRun Thanks it seems to work perfectly !

**Comment by sahib** [comment] 2016-11-10 18:10
I merged @SeeSpotRun's changes into the ``master`` branch.
This issue can probably be closed now, feel free to re-open if there are other problems.

**Closed by sahib** 2016-11-10 18:10 UTC
Labels: Discussion

**Comment by SeeSpotRun** [comment] 2016-11-10 21:42
Have updated docs to include --btrfs-clone [-r] (probably breaks translations)
